sudo: 'required'

language: java

services:
- docker

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t $DOCKER_USERNAME/echo-bot:latest . ;
      docker push $DOCKER_USERNAME/echo-bot ;
    fi