---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: echo
    spec:
      restartPolicy: Always

      containers:
        - name: echo
          image: eu.gcr.io/wire-bot/echo:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: echo-knows
                  key: token

            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: echo-knows
                  key: keystore_password


          volumeMounts:
            - name: cryptobox-echo
              mountPath: /var/lib/echo/crypto

            - name: echo-config
              mountPath: /etc/echo

          command:
            - "/usr/bin/java"
            - "-Ddw.server.applicationConnectors[1].keyStorePassword=$(KEYSTORE_PASSWORD)"
            - "-Ddw.server.applicationConnectors[1].keyStorePath=keystore.jks"
            - "-Ddw.auth=$(TOKEN)"
            - "-Ddw.cryptoDir=/var/lib/echo/crypto"
            - "-jar"
            - "echo.jar"
            - "server"
            - "/etc/echo/echo.yaml"

      volumes:
        - name: cryptobox-echo
          gcePersistentDisk:
            pdName: cryptobox-echo
            fsType: ext4

        - name: echo-config
          configMap:
            name: echo-config

---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    name: echo
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP